### ISSUE TITLE
Support other Database Backend to avoid using persistentVolumes

### ISSUE THREAD

**Issue by franznemeth** [fjogeleit/policy-reporter#129]
We would like to use the policy-reporter as an overview for our policy violations but the clusters policy-reporter should run in do not have the ability to provide persistent volumes.

Is there a possibility to implement the usage of another database backend such as postgresql?

**Comment by fjogeleit** [comment]
Hey, thanks for your request but policy-reporter does not need persistent volumes. It only uses emptyDir volumes. Or do you mean that emptyDir is also not available?

**Comment by franznemeth** [comment]
It uses the emptyDir to store an sqlite database right? Is this not a problem when the pod restarts/gets scheduled to a different node?

**Comment by fjogeleit** [comment]
No it’s not. The source of truth are the PolicyReport CRD resources. The sql database is just an internal mapping for the rest APIs to be able to sort and mainly filter the Reports and generate lists of available Policies, Categories and so on.

When policy reporter restarts or is recreated it just rebuild the internal schema based on the CRD resources. So nothing get’s lost.

Without the rest api SQLite is completely disabled because it is only needed for the APIs

**Comment by franznemeth** [comment]
Thank you for the explanation, that is great news for us. I will close this issue now, thanks again for your help!

**Comment by fjogeleit** [comment]
You’re welcome, let me know if you need any additional help.
