### ISSUE TITLE
Error page is not shown on 404

### ISSUE THREAD

**Issue by aslafy-z** [fjogeleit/policy-reporter#153]
When going to a wrong page in the UI, eg: /does-not-exist, we're getting a UI glitch instead of an error page:
![Screenshot from 2022-06-09 16-24-40](https://user-images.githubusercontent.com/8191198/172871020-0900ddbe-61d9-4ca7-8912-dcc8a8a00d58.png)
I'm using the latest release, [2.9.0](https://github.com/kyverno/policy-reporter/releases/tag/policy-reporter-2.9.0)

**Comment by fjogeleit** [comment]
Can you please reload the UI with CMD + Shift + R on Mac or ctrl + F5 on windows. This reloads without cache. In most cases this is an caching issue.

**Comment by aslafy-z** [comment]
I tried in a Private browser session and got the same (without the dark mode):
![image](https://user-images.githubusercontent.com/8191198/172872504-5c9c3749-6911-446a-993e-27f538a54f0e.png)

**Comment by fjogeleit** [comment]
Can you please check what you get as responses from the backend requests?

**Comment by tboussar** [comment]
We have the same issue on two new fresh installations using follwing versions for chart and images:
helm chart: "2.9.0"
policy_reporter: "2.6.0"
policy_reporter_ui: "1.4.0"
policy_reporter_kyverno_plugin: "1.3.1"

**Comment by fjogeleit** [comment]
Ah okay, sorry. I miss understood your issue. Okay for subpages which are not exist I also get this strange page. I will fix this.

**Comment by fjogeleit** [comment]
I created https://github.com/kyverno/policy-reporter-ui/pull/136 which will stop the wired rendering. It will return a HTTP 404 instead.

It is not that easy to render a custom 404 because Policy Reporter uses a Hash Router to support hosting under subpaths as well. So I am also not able to provide some kind of Back to Home button because I can not really guess the Home Page URL without knowledge about the hosting.

I will add a todo for me to create a static not found page with more details for the next major release. You can set the `ui.image.tag` to `1.4.2` for the fixed version. (Should be available in around ~15 minutes).

I will also create a new Helm Version with the fix soon.

**Comment by fjogeleit** [comment]
I released the fix with Helm Chart version 2.9.1 - Thanks for reporting
