### ISSUE TITLE
2.10.2 chart does not restart kyverno-plugin pod during upgrade

### ISSUE THREAD

**Issue by windowsrefund** [fjogeleit/policy-reporter#171]
This behavior was seen on a cluster running Kyverno 1.7.1. Deleting the pod in order for it to be recreating resulted in everything working as expected.

**Comment by fjogeleit** [comment]
That the KyvernoPlugin does not restart is the correct behavior when the KyvernoPlugin version stays the same and it is normally not necessary. That the registration of the CRD not works can be happened but it should retry. I am not sure if it does not work at all or was just be able to register on the first time because you had no policies running in your cluster.

I will improve this behavior in the next release but that the pod does not restart when the new Helm Version doesn't change anything for the KyvernoPlugin is expected.
