### ISSUE TITLE
Policy Reporter not aligned with Kyverno

### ISSUE THREAD

**Issue by alen-z** [fjogeleit/policy-reporter#438]
Policy Reporter reports all enforced policies as failing (PolicyReport) for a namespace which we are excluding in ClusterPolicy definition. `kyverno_policy_results_total` shows proper and relevant results, while Policy Reporter reports more failing policies.

Using latest versions.

Any mitigation? Thank you.

**Comment by fjogeleit** [comment]
Policy Reporter reflect the information given by your PolicyReports. So there should be PolicyReports in this excluded namespace. Did you exclude this namespace later on? Maybe Kyverno cleaned it not up correctly. You could manually delete the reports in this namespace.

But theres nothing really todo in PolicyReporter. Because the source of truth is generated by Kyverno only.

**Comment by alen-z** [comment]
Hey, thank you for a quick response! Just figured this out that it uses backgroundscanreports.kyverno.io resources to build it's knowledge base. I'll clean all backgroundscanreports.kyverno.io and see if it helps.

Yes, namespace exclusion was added later.

**Comment by alen-z** [comment]
Hey @fjogeleit, even after removing all backgroundscanreports.kyverno.io and PolicyReport resources, restarting Policy Reporter — still new PolicyReport is created.

**Comment by fjogeleit** [comment]
As mentioned `PolicyReport`s are created by Kyverno. Not Policy Reporter. So this is an issue by Kyverno / Policy definition.

**Comment by alen-z** [comment]
Got it, thank you.

Feel free to close since it's on me to do magic combining Policy Reporter metrics with `kyverno_policy_results_total` when it has certain value (not surfacing all Policy Reporter metrics, but those that are actually failing) and go to Kyverno to surface my concern.
