### ISSUE TITLE
Test UI Beta

### ISSUE THREAD

**Issue by allamand** [fjogeleit/policy-reporter#476]
Hi @fjogeleit,

I created this new issue to discuss the behaviour from the UI. I start with some screenshots of the UI which seams not finished:

on the first page, clicking on top-right "Kinds" or "Cluster Kinds":
![image](https://github.com/user-attachments/assets/65b54c8c-ad20-4d2c-831b-d61d38be9155)
![image](https://github.com/user-attachments/assets/91c1bf54-17a5-4749-bdbf-2e1ffaafb2b5)

The notification Targets also : 
![image](https://github.com/user-attachments/assets/88d192d0-d114-41d1-97ce-557bb4de0a48)

From the default Dashboard, I can see I have Fail checks in 2 namespaces, how I can quickly see the resources impacted ? If I click on it nothing happened, I don't see a list resources anywhere.
![image](https://github.com/user-attachments/assets/bbe771a2-4f3d-4e7a-bb6c-351a6810a942)

I'm only able to find this information if I click on a generate report, but it was lot more easier with previous version
![image](https://github.com/user-attachments/assets/4f5f1fe4-f1b7-4232-a507-f4f1bc2a8679)

**Comment by allamand** [comment]
I also note this error on policy-reporter startup:

```
policy-reporter-6c959cd6cc-md9j4 policy-reporter 1.7255321777513275e+09 info    sqlite connection created
policy-reporter-6c959cd6cc-md9j4 policy-reporter [bun]  10:29:37.752   SELECT                  381µs  SELECT "c"."id", "c"."version" FROM "policy_report_config" AS "c" WHERE (id = 1)          sqlite3.Error: no such table: policy_report_config 
```

**Comment by allamand** [comment]
Is it possible to start the UI with a banner ? if I have several clusters with their own instance, would be easier to differentiate them If I can put like the cluster-name in the helm value so it had specific banner on top

**Comment by fjogeleit** [comment]
Which browser do you use? Some behavior looks really strange. I have to check that. Also the namespaced results don't show up on your screen. If I see it correctly.

This is how it should look like

<img width="860" alt="Bildschirmfoto 2024-09-05 um 14 10 02" src="https://github.com/user-attachments/assets/f1a85033-c5d4-41d8-9544-627d9c07c0f5">

<img width="861" alt="Bildschirmfoto 2024-09-05 um 14 09 55" src="https://github.com/user-attachments/assets/6499448c-d469-4374-b6fc-10ec190d3395">

No banner but you can serve multiple cluster in a single UI instance, with a select to switch between them. If this is something interesting for your test case:

https://github.com/kyverno/policy-reporter/blob/3.x/charts/policy-reporter/values.yaml#L854

otherwise I take a look on showing the cluster name.

**Comment by allamand** [comment]
Oh you are right, I am testing on Safari on OSX. I just tried it on Chrome and the result is much better :) and I've found again the restuls i'm expecting.

for the multicluster, I would prefer not to as it open risk for thoses credentials

**Comment by fjogeleit** [comment]
Safari issues should be fixed now.
