### ISSUE TITLE
Question: Can this be used without cluster level access

### ISSUE THREAD

**Issue by teaglebuilt** [fjogeleit/policy-reporter#76]
If one is restricted to a namespace in their company from a SAAS platform / Kubernetes team. 
Could this be applied at the scope of a namespace? No ability to use any type of CRD or cluster level role access.

But if so, I could focus on applying policies for network policies, labels or so on...

**Comment by fjogeleit** [comment]
Hey, if you have only one namespace with your workloads and policy reporter within it could be working when you create your own Role and Rolebinding for the PolicyReporter ServiceAccount to access the `PolicyReport` CRD in this namespace.

For a subset of namespaces or if policy reporter is installed in another namespace as your workloads are, it is not possible because then you need a clusterrole and clusterrolebinding to access the `PolicyReport` CRD in these other namespaces.
